import type { Action } from './models';
export const prompts: Record<Action, string> = {
  translate:
    'Translate only; do not teach grammar. Translate the input INTO TRANSLATION_LANGUAGE, regardless of source language. Never choose a target based on explanation language. Provide exactly TWO translations in this order: (1) direct: a faithful literal translation close to the original wording, while remaining understandable; (2) natural: an idiomatic expression a native speaker would use, preserving meaning and tone without adding facts. Both must use TRANSLATION_LANGUAGE. Briefly explain their differences in EXPLANATION_LANGUAGE. If both versions naturally coincide, do not invent differences.\nReturn JSON: {"source_language":"detected language name","translation_language":"exact TRANSLATION_LANGUAGE label","translations":[{"text":"literal translation","type":"direct"},{"text":"idiomatic expression","type":"natural"}],"notes":["..."]}.',
  grammar:
    'Analyze grammatical correctness of the user\'s ORIGINAL sentence in its own language. Do NOT translate the sentence before analyzing it. analysis_text must preserve the user\'s exact input, including errors; analysis_origin must be original.\nFirst check for actual grammatical errors before explaining structure: tense, agreement, word order, articles, prepositions, missing or redundant components, and other rules applicable to the input language. If any error exists, set correct=false and explicitly identify each error in corrections. original must quote the exact faulty span from the input; corrected must show the corrected span in the same language; explanation must state why it is wrong and the relevant rule, not merely say it can be improved. Use minimal corrections that preserve intended meaning. Do not classify optional stylistic improvements as grammar errors and do not invent errors in correct sentences. If correct, do not announce that there are no errors; use summary only to describe the sentence pattern. Analyze the original sentence\'s structure as well. Only words and phrases belong in structure; never create a structure item for punctuation alone or explain punctuation as a sentence component. Preserve punctuation in analysis_text and within words or phrases. For EACH structure item, include translation: a concise contextual translation of its text into COMPONENT_TRANSLATION_LANGUAGE (the current app language). Translate the component itself, not its grammatical label. Keep text in the original language. Use COMPONENT_TRANSLATION_LANGUAGE for these translations regardless of EXPLANATION_LANGUAGE or TRANSLATION_LANGUAGE. All explanations use EXPLANATION_LANGUAGE.\nReturn JSON: {"source_language":"...","analysis_text":"exact original input","analysis_origin":"original","correct":true,"summary":"...","corrections":[{"original":"...","corrected":"...","explanation":"..."}],"structure":[{"text":"...","translation":"...","part":"...","role":"..."}],"grammar_points":[{"title":"...","explanation":"...","inflections":["base form","next form"]}]}.\nIf correct, corrections must be []. If incorrect, corrections must not be empty.',
  improve:
    'Evaluate the naturalness of the user\'s ORIGINAL sentence. reference_text must preserve the exact input; reference_origin must be original. Do NOT translate into another language before improving it.\nProvide natural, conversational and polite/formal alternatives IN THE SAME LANGUAGE AS THE INPUT, preserving the intended meaning. Explain tone, usage and differences in EXPLANATION_LANGUAGE. Each alternative\'s translation is an explanation-language gloss; the alternative\'s text stays in the input language.\nReturn JSON: {"source_language":"...","reference_text":"exact original input","reference_origin":"original","naturalness":"...","alternatives":[{"text":"same-language expression","style":"natural|conversational|polite","translation":"...","explanation":"..."}]}.',
};

export const japaneseReadingPrompt = `For Japanese text, provide its complete kana reading using hiragana (katakana loanwords may retain katakana), preserving punctuation. Use contextual readings of kanji, names, numbers and counters; never use romaji or translate the reading. For Japanese translation output add reading to EACH translations item. For Japanese original input in improve add reading to EACH alternatives item. For Japanese original input in grammar add analysis_reading for the original sentence, corrected_reading to EACH corrections item for its corrected span, and reading to EACH structure item. Omit these fields for non-Japanese text. Keep all existing fields and rules.`;
